---
name: Build Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  build-artifact:
    name: Build Artifact
    uses: ./.github/workflows/build-artifact.yml

  terraform-apply:
    name: Build CloudFront Environment
    uses: ./.github/workflows/terraform-apply.yml

  cloudfront-deploy:
    name: Deploy to CloudFront
    uses: ./.github/workflows/cloudfront-deploy.yml
    needs:
    - build-artifact
    - terraform-apply
    with:
      cloudfront_domain: ${{ needs.terraform-apply.outputs.cloudfront_domain }}
      cloudfront_distribution_id: ${{ needs.terraform-apply.outputs.cloudfront_distribution_id }}
      s3_bucket_name: ${{ needs.terraform-apply.outputs.s3_bucket_name }}
