---
name: Build

on:
  push:
    branches:
    - main

jobs:
  build-artifact:
    name: Build Artifact
    uses: ./.github/workflows/build-artifact.yml

  deploy-github-pages:
    runs-on: ubuntu-24.04

    needs: build-artifact

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://bpm.robojackets.org

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
